global:
  pattern: idp
  singleArgoCD: true
  secretLoader:
    disabled: true
main:
  patternsOperator:
    enableSubscription: false
  clusterGroupName: idc
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
