global:
  pattern: agent-identity-canary
  singleArgoCD: true
  secretLoader:
    disabled: true
main:
  patternsOperator:
    enableSubscription: false
  clusterGroupName: agent-identity
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
