source:
  git:
    uri: "https://github.com/NVIDIA/NemoClaw.git"
    ref: "fb01aff8ed67596dcdfe38cb6f5dccdcba301a33"

build:
  nodeImage: "node:22-trixie-slim"
  maxOpenshellVersion: "0.0.110"

output:
  imageStreamTag: "nemoclaw-cli:latest"
