{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: governance-interceptor-policy
  labels:
    app.kubernetes.io/name: governance-interceptor
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  policy.yaml: |
{{ .Files.Get "policy.yaml" | indent 4 }}
{{- range .Values.profiles }}
  {{ . }}-profile.yaml: |
{{ $.Files.Get (printf "profiles/%s.yaml" .) | indent 4 }}
{{- end }}
{{- end }}
