openshell:
  version: "0.0.96"
  gatewayImage: "quay.io/opendatahub/odh-openshell-gateway@sha256:1a9bf1b5064befde7d5b392e657951ac115eabf255bcff1e9c0d8b17e8142a17"
  supervisorImage: "quay.io/opendatahub/odh-openshell-supervisor@sha256:0e5a9ae58295a5072f22bd3ea09cd083caab512fe2193e1b0a0f2d45196192b7"
  pipIndexUrl: "https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.6-EA1/cpu-ubi9-test/simple/"

build:
  builderImage: "registry.fedoraproject.org/fedora:44"
  fedoraCloud: "https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2"
  memoryLimit: "4Gi"

output:
  imageStreamTag: "openshell-gateway:latest"

goldenImage:
  enabled: true
  diskSize: 40Gi
  storageClassName: ""
