openshell:
  version: "0.0.96"
  gatewayImage: "quay.io/opendatahub/odh-openshell-gateway@sha256:38e22f33f8498ddd3f2429599d1e0c12d468d834e4bf31e681474d93fd70f696"
  supervisorImage: "quay.io/opendatahub/odh-openshell-supervisor@sha256:4cc8c56eb7a378511c08acdd542181447fca45e5fc34fc4c2403bb46224faf84"
  pipIndexUrl: "https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.6-EA1/cpu-ubi9-test/simple/"

build:
  builderImage: "registry.fedoraproject.org/fedora:44"
  fedoraCloud: "https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2"
  memoryLimit: "4Gi"

output:
  imageStreamTag: "openshell-gateway:latest"

goldenImage:
  enabled: true
  diskSize: 40Gi
  storageClassName: ""
